default:
  image: node:gallium-alpine

lint:
  stage: test
  interruptible: true
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules/
    - key: yarn-cache
      paths:
        - ".yarn"
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn tsc
    - yarn lint:style
    - yarn lint:script
    # - yarn test
  only:
    - merge_requests

build:
  image: docker:latest
  stage: build
  interruptible: true
  resource_group: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - develop
    - staging
    - uat

build-main:
  image: docker:latest
  stage: build
  interruptible: true
  resource_group: build-main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
