name: Node.js CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder .yarn

      - name: TypeScript compile
        run: yarn tsc

      - name: Lint styles
        run: yarn lint:style

      - name: Lint scripts
        run: yarn lint:script

      # Uncomment the following lines to run tests
      # - name: Run tests
      #   run: yarn test
